version: '3.7'

networks:
  internal:
    external: false

services:      
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 -w 2 config.wsgi:application
    volumes:
      - .:/usr/src/app/
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.settings
      - DEBUG=True
    expose:
      - 8000
    networks:
      - internal
      
  nginx:
    image: nginx:1.17.10-alpine
    volumes:
      - ./website/static:/usr/src/app/ws-kevinharper/website/static/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - internal

